include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.freezed.dart
    - lib/**.g.dart
    - lib/**.gr.dart
    - lib/**.gen.dart

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
